name: Android APK Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev git

      - name: Install Cython, Buildozer, and p4a
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.36 buildozer "python-for-android==2024.1.21"

      - name: Set up Android SDK cmdline-tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept SDK licenses and install components
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;30.0.3" \
            "build-tools;36.0.0"

      - name: Download and extract Android NDK r25b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME
          echo "ANDROIDNDK=$HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "$HOME/android-ndk-r25b" >> $GITHUB_PATH

      - name: Copy SDK licenses to buildozer path
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
          cp -r $HOME/android-sdk/licenses/* $HOME/.buildozer/android/platform/android-sdk/licenses/ || true

      - name: Clean previous buildozer and SDK state
        run: |
          rm -rf .buildozer bin
          rm -rf $HOME/.buildozer/android/platform/android-sdk

      - name: List build-tools versions (debug)
        run: ls -lh $HOME/android-sdk/build-tools || true

      - name: Build APK
        env:
          ANDROIDNDK: ${{ env.HOME }}/android-ndk-r25b
          ANDROID_NDK_HOME: ${{ env.HOME }}/android-ndk-r25b
          ANDROID_HOME: ${{ env.HOME }}/android-sdk
          PATH: ${{ env.PATH }}:${{ env.HOME }}/android-ndk-r25b:${{ env.HOME }}/android-sdk/build-tools/30.0.3:${{ env.HOME }}/android-sdk/platform-tools:${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk