
name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk
          python -m pip install --upgrade pip
          pip install Cython==0.29.36 buildozer




      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install --user Cython==0.29.36
          pip install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH
    
          

      - name: Install Android SDK
        run: |
          mkdir -p "$HOME"/android-sdk/cmdline-tools
          cd "$HOME"/android-sdk/cmdline-tools
          curl -sSLo sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip sdk.zip
          rm sdk.zip
          mv cmdline-tools latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set environment for Android
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Init buildozer spec (skip if exists)
        run: |
          test -f buildozer.spec || buildozer init

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
