name: Android APK Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev

      - name: Install Cython and Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Initialize Buildozer spec
        run: buildozer init || true

      - name: Build Android APK
        run: buildozer android debug